CREATE TABLE TEST(
    TNO NUMBER PRIMARY KEY
  , TNAME VARCHAR2(20)
  , TDATE DATE
);

CREATE SEQUENCE SEQ_TNO
    NOCACHE;
    
INSERT INTO TEST VALUES(SEQ_TNO.NEXTVAL, '테스트1', '2024-07-01');
INSERT INTO TEST VALUES(SEQ_TNO.NEXTVAL, '테스트2', '2024-07-07');
INSERT INTO TEST VALUES(SEQ_TNO.NEXTVAL, '테스트3', '2024-07-20');

COMMIT;

CREATE TABLE MEMBER(
    USER_NO     NUMBER PRIMARY KEY
  , USER_ID     VARCHAR(15)     NOT NULL UNIQUE
  , USER_PWD    VARCHAR(15)     NOT NULL
  , USER_NAME   VARCHAR(20)     NOT NULL
  , GENDER      CHAR(1)         NULL CHECK(GENDER IN ('M', 'F'))
  , AGE         NUMBER          NULL
  , EMAIL       VARCHAR2(40)    NULL
  , PHONE       CHAR(11)        NULL
  , HOBBY       VARCHAR2(50)    NULL
  , REGIST_DATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE SEQ_UNO
    START WITH 10000
    NOCACHE;
    
INSERT
    INTO MEMBER(USER_NO, USER_ID, USER_PWD, USER_NAME, GENDER, AGE, EMAIL, PHONE, HOBBY)
 VALUES (SEQ_UNO.NEXTVAL, 'admin', '1234', '관리자', 'M', 45, 'admin@br.com', '01011112222', null);

INSERT
    INTO MEMBER(USER_NO, USER_ID, USER_PWD, USER_NAME, GENDER, AGE, EMAIL, PHONE, HOBBY)
 VALUES (SEQ_UNO.NEXTVAL, 'user01', 'pass01', '홍길동', 'F', 23, 'user01@br.com', '01022223333', '등산,영화');
 
commit; 

SELECT * FROM MEMBER;








 
 
 
 
 
 
 